name: Deploy Pages
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    uses: doriannaujokat/github-workflows/.github/workflows/pages-typescript.yml@main
